[tool.sqlfluff.core]
templater = "jinja"
dialect = "bigquery"
sql_file_exts = ".sql,.sql.j2,.dml,.ddl"
exclude_rules = [ 
    "CP02", # Inconsistent capitalisation of unquoted identifiers.
    "ST06", # Select wildcards then simple targets before calculations and aggregates.
]

[tool.sqlfluff.convention.quoted_literal]
preferred_quoted_literal_style = "single_quotes"

[tool.sqlfluff.indentation]
indented_joins = false
indented_using_on = true
template_blocks_indent = false

[tool.sqlfluff.layout.type.comma]
line_position = "leading"

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "upper"

[tool.sqlfluff.rules.capitalisation.functions]
extended_capitalisation_policy = "upper"

[tool.sqlfluff.rules.capitalisation.literals]
# Null & Boolean Literals
capitalisation_policy = "upper"

[tool.sqlfluff.rules.capitalisation.types]
# Data Types
extended_capitalisation_policy = "upper"

[tool.sqlfluff.structure.subquery]
# no subqueries in FROM and JOIN, wse CTEs instead
forbid_subquery_in = "both"

[tool.sqlfluff.templater]
unwrap_wrapped_queries = true

[tool.sqlfluff.templater.jinja]
apply_dbt_builtins = true